DROP DATABASE IF EXISTS CLAIMS_DB;
CREATE DATABASE CLAIMS_DB;

CREATE TABLE CLAIMS_DB.NON_SUBMITTED_CLAIMS(
  CLAIM_ID VARCHAR(100) PRIMARY KEY,
  CREATION_DATE DATETIME DEFAULT NOW(),
  CLAIM_JSON MEDIUMTEXT   
);

CREATE TABLE CLAIMS_DB.non_submitted_claims_photos (
  photo_Id INT NOT NULL AUTO_INCREMENT,
  claim_id VARCHAR(100) NOT NULL,
  photo_Name VARCHAR(200) NULL,
  PRIMARY KEY (photo_Id),
  CONSTRAINT fk_claim_Id
	FOREIGN KEY (claim_id) REFERENCES NON_SUBMITTED_CLAIMS (CLAIM_ID)
);

CREATE TABLE CLAIMS_DB.CLAIMS_TABLE_VIEW (
  VIEW_ID INT PRIMARY KEY AUTO_INCREMENT,
  VIEW_NAME VARCHAR(40) NOT NULL,
  CREATED_BY VARCHAR(40) NULL,
  CREATED_DATE DATETIME,
  MODIFIED_BY VARCHAR(40) NULL,
  MODIFIED_DATE DATETIME,
  FIELDS_TO_DISPLAY VARCHAR(1500),
  VISIBILITY VARCHAR(10)
 );